// src/components/RepoList.vue
<script setup>
import { ref, computed, onMounted } from 'vue';
import { RouterLink } from 'vue-router';
import GithubIcon from './icons/GithubIcon.vue';

const searchQuery = ref('');
const repos = ref([]);
const status = ref('loading');
const currentPage = ref(1);
const REPOS_PER_PAGE = 12;

const filteredRepos = computed(() =>
  repos.value.filter((repo) => repo.name.toLowerCase().includes(searchQuery.value))
);

const totalNumberOfRepos = computed(() => filteredRepos.value.length);
const numberOfPages = computed(() => Math.ceil(totalNumberOfRepos.value / REPOS_PER_PAGE));

const isPrevButtonDisabled = computed(() => currentPage.value === 1);
const isNextButtonDisabled = computed(() => currentPage.value === numberOfPages.value);

function fetchRepos() {
  status.value = 'loading';
  fetch(`https://api.github.com/users/joshua-emmanuel/repos?per_page=10000`)
    .then((response) => response.json())
    .then((data) => {
      repos.value = data;
      status.value = 'done';
    })
    .catch(() => {
      status.value = 'error';
    });
}

function onPaginationButtonClick(pageNumber) {
  currentPage.value = pageNumber;
}

function onSearchInputChange(event) {
  currentPage.value = 1;
  searchQuery.value = event.target.value.trim().toLowerCase();
}

onMounted(() => {
  fetchRepos();
});
</script>

<template>
  <section class="repo-list">
    <div class="wrapper">
      <form class="repo-list__search">
        <svg
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="currentColor"
        >
          <path
            fillRule="evenodd"
            d="M10.5 3.75a6.75 6.75 0 1 0 0 13.5 6.75 6.75 0 0 0 0-13.5ZM2.25 10.5a8.25 8.25 0 1 1 14.59 5.28l4.69 4.69a.75.75 0 1 1-1.06 1.06l-4.69-4.69A8.25 8.25 0 0 1 2.25 10.5Z"
            clipRule="evenodd"
          />
        </svg>

        <input
          @input="onSearchInputChange"
          type="text"
          name="search-input"
          placeholder="Search for repos"
        />
      </form>
      <div class="repos" v-if="filteredRepos.length > 0 && status === 'done'">
        <div
          v-for="repo in filteredRepos.slice(
            (currentPage - 1) * REPOS_PER_PAGE,
            currentPage * REPOS_PER_PAGE
          )"
          :key="repo.id"
        >
          <div className="repo">
            <div className="repo__title">
              <GithubIcon />
              <h2>{{ repo.name }}</h2>
            </div>
            <RouterLink :to="{ path: `/repos/${repo.name}` }"></RouterLink>
          </div>
        </div>
      </div>
      <div v-else-if="status === 'loading'">
        <p class="text-center">Loading Repositories</p>
      </div>
      <div v-else-if="status === 'error'" class="error-message text-center">
        <p>Oops, something went wrong while loading the repositories.</p>
        <p>Please check your internet connection and try again later</p>
        <button @click="fetchRepos">Retry</button>
      </div>
      <div v-if="searchQuery && filteredRepos.length === 0 && status === 'done'">
        <p class="text-center">No repos found for search query '{{ searchQuery }}'</p>
      </div>
      <div class="pagination" v-if="filteredRepos.length > 0">
        <button :disabled="isPrevButtonDisabled" @click="onPaginationButtonClick(currentPage - 1)">
          Prev
        </button>
        <button
          v-for="number in numberOfPages"
          @click="onPaginationButtonClick(number)"
          :key="number"
          :class="currentPage === number ? 'active' : ''"
        >
          {{ number }}
        </button>
        <button :disabled="isNextButtonDisabled" @click="onPaginationButtonClick(currentPage + 1)">
          Next
        </button>
      </div>
    </div>
  </section>
</template>

<style scoped>
*:focus {
  outline-color: #082f49;
}

.repo-list {
  margin-block: 3rem;
}

.repo-list__search {
  margin-bottom: 2rem;
  width: 100%;
  position: relative;
}

.repo-list__search svg {
  position: absolute;
  left: 1rem;
  top: 50%;
  transform: translateY(-50%);

  width: 20px;
  height: 20px;
  fill: #777e8a;
}

.repo-list__search input {
  width: 100%;
  padding: 1rem;
  padding-left: 2.5rem;
  border: 1px solid rgba(0, 0, 0, 0.15);
  border-radius: 0.5rem;
  background-color: white;
}

.repo-list__search input:hover {
  border: 1px solid rgba(0, 0, 0, 0.35);
}

.repo-list__search input:focus {
  outline-color: #082f49;
}

.repos {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 1rem;
}

.repo {
  position: relative;
  padding: 1.5rem;
  border-radius: 0.5rem;
  color: #082f49;
  background-color: #fff;
  box-shadow:
    0 0 0 1px rgba(0, 0, 0, 0.08),
    0 4px 6px rgba(0, 0, 0, 0.04);
  transition: box-shadow 0.15s ease;
}

.repo__title {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.repo__title img {
  width: 8%;
}

.repo h2 {
  font-size: 1.25rem;
}

.repo a {
  text-decoration: none;
  display: block;
  position: absolute;
  inset: 0;
  z-index: 1;
}

.repo:has(a:hover) {
  box-shadow:
    0 0 0 1px rgba(0, 0, 0, 0.08),
    0 6px 14px rgba(0, 0, 0, 0.08);
}

@media (max-width: 75em) {
  .repos {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (max-width: 50em) {
  .repos {
    grid-template-columns: 1fr;
  }
}

.pagination {
  margin-block: 2rem;
  display: flex;
  gap: 0.5rem;
  justify-content: center;
}

.pagination button {
  padding: 0.5rem 0.75rem;
  border: 1px solid #082f49;
  border-radius: 0.25rem;
  background-color: #fff;
  transition: all 200ms ease-in;
}

.pagination button.active,
.pagination button:not([disabled]):hover {
  color: white;
  background-color: #082f49;
}

.pagination button[disabled] {
  cursor: not-allowed;
  opacity: 0.5;
}
</style>

// src/RepoList.jsx
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import "./assets/css/RepoList.css";
import githubMark from "./assets/images/github-mark.svg";

function RepoList() {
  const [repos, setRepos] = useState([]);
  const [originalRepos, setOriginalRepos] = useState([]);
  const [currentPage, setCurrentPage] = useState(1);
  const [showViewMore, setShowViewMore] = useState(true);
  const [showViewMoreBtn, setShowViewMoreBtn] = useState(true);
  const [fetchingRepos, setFetchingRepos] = useState(false);
  const [searchingRepos, setSearchingRepos] = useState(false);
  const [reposLoadingState, setReposLoadingState] = useState(
    "Loading repositories..."
  );

  const fetchRepos = () => {
    fetch(
      `https://api.github.com/users/joshua-emmanuel/repos?per_page=6&page=${currentPage}`
    )
      .then((response) => response.json())
      .then((data) => {
        if (data.length === 0) {
          setShowViewMore(false);
        } else {
          setOriginalRepos([...originalRepos, ...data]);
          setRepos([...repos, ...data]);
          setShowViewMore(true);
        }
        setFetchingRepos(false);
      });
  };

  const filterRepos = (searchInput) => {
    setSearchingRepos(true);
    if (searchInput === "") {
      setRepos(originalRepos);
      setShowViewMoreBtn(true);
      setSearchingRepos(false);
      return;
    }
    fetch(`https://api.github.com/users/joshua-emmanuel/repos`)
      .then((response) => response.json())
      .then((data) => {
        const filteredRepos = data.filter((data) =>
          data.name.toLowerCase().includes(searchInput)
        );
        setCurrentPage(1);
        setSearchingRepos(false);
        setShowViewMoreBtn(false);
        setRepos(filteredRepos);
        if (filteredRepos.length === 0) setReposLoadingState("No repos found");
      });
  };

  useEffect(() => {
    fetchRepos();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentPage]);

  const viewMore = () => {
    setCurrentPage(currentPage + 1);
    setFetchingRepos(true);
  };

  function debounce(callback, wait, immediate) {
    let timeout;
    return function () {
      const context = this;
      const args = arguments;
      const later = function () {
        timeout = null;
        if (!immediate) callback.apply(context, args);
      };
      const callNow = immediate && !timeout;
      clearTimeout(timeout);
      timeout = setTimeout(later, wait);
      if (callNow) callback.apply(context, args);
    };
  }

  const searchForRepo = debounce((event) => {
    event.preventDefault();
    const inputValue = event.target.value.trim().toLowerCase();
    filterRepos(inputValue);
  }, 500);

  return (
    <section className="repo-list">
      <div className="wrapper">
        <form className="repo-list__search">
          <svg
            className={searchingRepos ? "hidden" : ""}
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
          >
            <path
              fillRule="evenodd"
              d="M10.5 3.75a6.75 6.75 0 1 0 0 13.5 6.75 6.75 0 0 0 0-13.5ZM2.25 10.5a8.25 8.25 0 1 1 14.59 5.28l4.69 4.69a.75.75 0 1 1-1.06 1.06l-4.69-4.69A8.25 8.25 0 0 1 2.25 10.5Z"
              clipRule="evenodd"
            />
          </svg>

          <svg
            className={`spinner ${searchingRepos ? "" : "hidden"}`}
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            fill="#000000"
            viewBox="0 0 256 256"
          >
            <path d="M136,32V64a8,8,0,0,1-16,0V32a8,8,0,0,1,16,0Zm37.25,58.75a8,8,0,0,0,5.66-2.35l22.63-22.62a8,8,0,0,0-11.32-11.32L167.6,77.09a8,8,0,0,0,5.65,13.66ZM224,120H192a8,8,0,0,0,0,16h32a8,8,0,0,0,0-16Zm-45.09,47.6a8,8,0,0,0-11.31,11.31l22.62,22.63a8,8,0,0,0,11.32-11.32ZM128,184a8,8,0,0,0-8,8v32a8,8,0,0,0,16,0V192A8,8,0,0,0,128,184ZM77.09,167.6,54.46,190.22a8,8,0,0,0,11.32,11.32L88.4,178.91A8,8,0,0,0,77.09,167.6ZM72,128a8,8,0,0,0-8-8H32a8,8,0,0,0,0,16H64A8,8,0,0,0,72,128ZM65.78,54.46A8,8,0,0,0,54.46,65.78L77.09,88.4A8,8,0,0,0,88.4,77.09Z"></path>
          </svg>

          <input
            type="text"
            name="search-input"
            placeholder="Search for repos"
            onChange={searchForRepo}
          />
        </form>
        {repos.length > 0 ? (
          <>
            <div className="repos">
              {repos.map((repo, index) => (
                <div className="repo" key={index}>
                  <div className="repo__title">
                    <img src={githubMark} alt="" />
                    <h2>{repo.name}</h2>
                  </div>
                  <Link
                    aria-label={`Open ${repo.name}`}
                    to={`/repo/${repo.name}`}
                  ></Link>
                </div>
              ))}
            </div>
            {fetchingRepos && (
              <div className="loading-more-repos">
                <p>Loading...</p>
              </div>
            )}
            <div className="view-more-div">
              {showViewMoreBtn && (
                <button
                  className="view-more-btn"
                  onClick={viewMore}
                  data-disabled={!showViewMore}
                >
                  {showViewMore ? "View More Repos" : "No more repos"}
                </button>
              )}
            </div>
          </>
        ) : (
          <div className="loading-repos">
            <p>{reposLoadingState}</p>
          </div>
        )}
      </div>
    </section>
  );
}

export default RepoList;
